### ISSUE TITLE
mandatory doesnt work

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_translatedfile#20]
mandatory doesnt work

**Comment by Ainschy** [comment]
Gibts hier irgendwelche Bewegungen zu dem Bug?

**Comment by zonky2** [comment]
nein - hat bisher niemanden so gestört, dass mal ein PR eingereicht wurde oder Beauftragung...

**Comment by zonky2** [comment]
add at https://github.com/MetaModels/attribute_translatedfile/blob/master/src/Attribute/TranslatedFile.php#L327

**Comment by zonky2** [comment]
Add mandatory in MM 2.2
